
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: burlunch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: ghcr.io/lavliet2/burlunch-webapp:latest
          ports:
            - containerPort: 5001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://*:5001"
            - name: ApiBaseUrl
              value: "http://authapi:8081"
  imagePullSecrets:
    - name: ghcr-secret              
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
