version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: burservis
      POSTGRES_DB: BurLunchDb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  authapi:
    build:
      context: .
      dockerfile: BurLunch.AuthAPI/Dockerfile
    container_name: burlunch-authapi
    depends_on:
      - postgres
    environment:
      ASPNETCORE_PORT: 8082
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=BurLunchDb;Username=postgres;Password=burservis"
    ports:
      - "8082:8082"

  webapp:
    build:
      context: .
      dockerfile: BurLunch.WebApp/Dockerfile
    container_name: burlunch-webapp
    depends_on:
      - authapi
    environment:
      ASPNETCORE_PORT: 5000
      ApiBaseUrl: "http://burlunch-authapi:8082"
    ports:
      - "5000:5000"

volumes:
  postgres-data:
