name: Deploy BurLunch App

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Backup existing deployment
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << EOF
          mkdir -p /home/lavliet/BackUp/BurLunch/
          docker save -o /home/lavliet/BackUp/BurLunch/burlunch-backup-$(date +%Y%m%d%H%M%S).tar burlunch-app-webapp burlunch-app-authapi postgres-container
          docker exec postgres-container pg_dump -U postgres -d BurLunchDb > /home/lavliet/BackUp/BurLunch/burlunch-db-backup-$(date +%Y%m%d%H%M%S).sql
          EOF

      - name: Deploy to Ubuntu Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << 'EOF'
          cd ~/burlunch-app
          docker-compose down
          docker-compose up -d --build
          EOF
