name: Deploy BurLunch App to Kubernetes!

on:
  workflow_run:
    workflows:
      - Deploy BurLunch App
    types:
      - completed

jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Kubernetes via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << 'EOF'
          rm -rf /home/lavliet/burlunch-app
          git clone https://github.com/Lavliet2/BurLunch.git /home/lavliet/burlunch-app
          cd /home/lavliet/burlunch-app
          kubectl apply -f /home/lavliet/burlunch-app/.k8s/postgres-deployment.yaml
          kubectl apply -f /home/lavliet/burlunch-app/.k8s/authapi-deployment.yaml
          kubectl apply -f /home/lavliet/burlunch-app/.k8s/webapp-deployment.yaml


