name: Deploy BurLunch App to Kubernetes

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Kubernetes via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << 'EOF'
          kubectl apply -f /path/to/k8s-manifests/postgres-deployment.yaml
          kubectl apply -f /path/to/k8s-manifests/authapi-deployment.yaml
          kubectl apply -f /path/to/k8s-manifests/webapp-deployment.yaml
          EOF

