name: Deploy BurLunch App

on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Backup existing deployment
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << 'EOF'
          docker-compose down 
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          
          # Создание папки для бэкапов, если её ещё нет
          mkdir -p /home/lavliet/BackUp/BurLunch
          
          # Перемещение старой версии приложения в папку BackUp с добавлением метки времени
          mv /home/lavliet/burlunch-app /home/lavliet/BackUp/BurLunch/burlunch-app-$TIMESTAMP          
          EOF

      - name: Deploy to Ubuntu Server
        run: |
          git clone https://github.com/Lavliet2/BurLunch.git /home/lavliet/burlunch-app
          
          # Переход в папку с проектом и запуск деплоя
          cd /home/lavliet/burlunch-app
          docker-compose up -d --build
          EOF

          # ssh -o StrictHostKeyChecking=no -p 2222 lavliet@178.72.83.217 << 'EOF'
          # cd ~/burlunch-app
          # git pull origin main          
          # docker-compose down
          # docker-compose up -d --build
          # EOF
